#!/usr/bin/env bash
#bash script that redirects to another server

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
echo "server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirect_me
sudo service nginx restart
