#!/usr/bin/env bash
#script to configure Nginx for a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ =404;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/custom_404
sudo service nginx restart
