#!/usr/bin/env bash
#script that configures Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get install -y nginx
echo "server {
    listen 80 default_server;
    server_name _;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    add_header X-Served-By \$hostname;
}" | sudo tee /etc/nginx/sites-available/custom_header
sudo service nginx restart
