#!/usr/bin/env bash
#script that configures Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
server {
    listen 80 default_server;
    server_name _;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    # Custom HTTP response header
    add_header X-Served-By \$hostname;
}
EOL
sudo service nginx reload
