#!/usr/bin/env bash
#script that displays listening ports

lsof -i -P -n | grep LISTEN | awk '{print $2, $1, $9}' | while read -r line
do
	pid=$(echo "$line" | awk '{print $1}')
	program=$(echo "$line" | awk '{print $2}')
	port=$(echo "$line" | awk '{split($3, a, ":"); print a[length(a)]}')

	echo "Port: $port, PID: $pid, Program: $program"
done
