#!/usr/bin/env bash
# Script to ensure Nginx is running and listening on port 80
sudo apt-get -y update
sudo apt-get -y install nginx
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
