#!/usr/bin/env bash
#script that ensures niginc is runnning and listening on port 80

sed -i '/listen 80 default_server;/a listen [::]:80 default_server;' /etc/nginx/sites-available/default
service nginx restart
