#!/usr/bin/env bash
# Script to ensure Nginx is running and listening on port 80

sed -i "/server_name _;/a \\\tlisten [::]:80 default_server;" /etc/nginx/sites-available/default
sudo service nginx restart
