#!/usr/bin/env bash
#script that does fizzbuzz

for ((i=1; i<=100; i++))
do
	if ((i % 3 == 0)) && ((i % 5 == 0))
	then
		echo -e "FizzBuzz"
	elif ((i % 3 == 0))
	then
		echo -e "Fizz"
	elif ((i % 5 == 0))
	then
		echo -e "Buzz"
	else
		echo -e "$i"
	fi
done
