#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 and other stuff

count=1
while ((count<=20))
do
	case "$count" in
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	echo $count
	((count++))
done
