#!/usr/bin/env bash
#script that prints mins, hours and such

hours=0
minutes=1
while ((hours!=13))
do
    echo "Hour: $hours"
    ((hours++))
    while ((minutes!=60))
    do
        echo $minutes
        ((minutes++))
    done
    ((minutes=1))
done
