#!/usr/bin/env bash
#script that makes sure nginx is running with nginx user
sudo -u nginx service nginx stop
sudo -u nginx service apache2 stop
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
